### ISSUE TITLE
gorilla-cli failed to install

### ISSUE THREAD

**Issue by MrUnknown789556** [gorilla-llm/gorilla-cli#11]
I just tried to install gorilla-cli. It didn't completed.

Error log attached here.

[Install log.txt](https://github.com/gorilla-llm/gorilla-cli/files/12042947/Install.log.txt)

**Comment by ShishirPatil** [comment]
Thanks for trying Gorilla and thanks for the error log @MrUnknown789556. I just tore a new release. So can you try it out and let me know if you run into any issues:

```bash
rm ~/.gorilla-cli-* && pip uninstall gorilla-cli
pip install gorilla-cli
```

**Comment by anaman** [comment]
I had to install with
" pip install gorilla-cli --break-system-packages "
Because i had this error
"~/gorilla-cli$ pip install gorilla-cli
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification."

Works now but i guess it comes with the experimental nature of this adventure. :-)

**Comment by ShishirPatil** [comment]
Thanks for this @anaman Yeah, it is research prototype 🙂 and your trying it out means a lot to us ❤️  
BTW the above maybe happening due to apt managing your python. One potential solution could be to use virtual environments like virtualenv or conda. Either way, glad it worked!
